defaults: &defaults
  working_directory: ~/usemodalwallet
  docker:
    - image: circleci/node:12.16

aliases:
  - &restore_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-v1-{{ checksum "yarn.lock" }}
        - yarn-packages-v1-
        - yarn-packages-v1-

version: 2.0

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Install Dependencies
          command: |
            echo 'Installing dependencies'
            yarn --frozen-lockfile
      - save_cache: 
          name: Save Yarn Package Cache
          paths:
            - node_modules
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
  
  lint-and-format: 
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Lint
          command: yarn lint
  
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Run unit tests with JUnit as reporter
          command: yarn test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  build: 
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Build
          command: yarn compile

  # deploy: 
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - *restore_cache
  #     - run:
  #         name: Deploy
  #         command: yarn deploy
  # publish: 
  #   docker: *nodejs-docker-image
  #   steps:
  #     - checkout
  #     - *restore_cache
  #     - run: 
  #         name: Compile all
  #         command: yarn compile
  #     - run: 
  #         name: Discard changes // Truffle BUG
  #         command: git stash
  #     - run: 
  #         name: Prepare
  #         command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
  #     - run:
  #         name: Publish all
  #         command: yarn publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - setup
      - lint-and-format:
          requires:
            - setup
      - tests:
          requires:
            - setup
      # - publish:
      #     context: SolidStudio
      #     requires:
      #       - lint-and-format
      #       - tests
      #     filters:
      #       branches:
      #         only: master